Layout/AlignHash:
  Enabled: false
Layout/EmptyLineAfterGuardClause:
  Enabled: false
Layout/SpaceAroundOperators:
  Enabled: false
Lint/ShadowedArgument:
  Enabled: false
Metrics/AbcSize:
  Max: 50
Metrics/BlockLength:
  Max: 50
Metrics/CyclomaticComplexity:
  Max: 50
Metrics/LineLength:
  Enabled: false
Metrics/MethodLength:
  Max: 50
Metrics/PerceivedComplexity:
  Max: 50
Layout/AlignArray:
  Enabled: false
Naming/AccessorMethodName:
  Enabled: false
Naming/HeredocDelimiterNaming:
  Enabled: false
Naming/UncommunicativeMethodParamName:
  Enabled: false
Style/Encoding:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false
Style/FormatStringToken:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/ParallelAssignment:
  Enabled: false
Style/NumericLiterals:
  Enabled: false
Style/Semicolon:
  Enabled: false
Style/StringLiterals:
  Enabled: false
Style/TrailingCommaInArguments:
  Enabled: false
Style/TrailingCommaInArrayLiteral:
  Enabled: false
Style/TrailingCommaInHashLiteral:
  Enabled: false
Style/WordArray:
  Enabled: false
Style/UnpackFirst:
  Enabled: false
