Layout/AlignHash:
  Enabled: false
Layout/EmptyLineAfterGuardClause:
  Enabled: false
Lint/ShadowedArgument:
  Enabled: false
Metrics/LineLength:
  Enabled: false
Style/Encoding:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/ParallelAssignment:
  Enabled: false
