#!/bin/sh

my_install='go get -v -u'

$my_install github.com/BurntSushi/toml/cmd/tomlv #toml validator
$my_install github.com/github/hub #github helper <https://github.com/github/hub>
$my_install github.com/golang/lint/golint #used by emacs flycheck
$my_install github.com/jgrahamc/httpdiff #diff http requests <https://github.com/jgrahamc/httpdiff>
$my_install github.com/jingweno/ccat #colorizing cat <https://github.com/jingweno/ccat>
$my_install github.com/kahing/goofys #mount s3 file system
$my_install github.com/kisielk/errcheck #used by emacs flycheck
$my_install github.com/laurent22/massren #rename multiple files using text editor <https://github.com/laurent22/massren>
$my_install github.com/lukasmartinelli/pgfutter #import csv and json into postgresql
$my_install github.com/monochromegane/the_platinum_searcher #ag and ack replacement <https://github.com/monochromegane/the_platinum_searcher>
$my_install github.com/noraesae/orange-cat/cmd/orange #markdown preview
$my_install github.com/nsf/gocode #used by emacs auto complete
$my_install github.com/rakyll/boom #http load generator (a-la ab)
$my_install github.com/rapidloop/rtop #remote top over ssh
$my_install github.com/rlmcpherson/s3gof3r/gof3r #s3 client
$my_install github.com/rogpeppe/godef #used by emacs for jump to the definition of the expression at point
$my_install github.com/russross/blackfriday-tool #markdown
$my_install github.com/schachmat/wego #weather
$my_install golang.org/x/tools/cmd/godoc #documentation
