#!/bin/sh

packages="$packages github.com/BurntSushi/toml/cmd/tomlv" #toml validator
packages="$packages github.com/cortesi/devd/cmd/devd" #local http/webserver for developers
packages="$packages github.com/danil/tgtm" #tweets go to mail (twitter client)
packages="$packages github.com/github/hub" #github helper <https://github.com/github/hub>
packages="$packages github.com/golang/lint/golint" #used by emacs flycheck
packages="$packages github.com/jgrahamc/httpdiff" #diff http requests <https://github.com/jgrahamc/httpdiff>
packages="$packages github.com/jingweno/ccat" #colorizing cat <https://github.com/jingweno/ccat>
packages="$packages github.com/kahing/goofys" #mount s3 file system
packages="$packages github.com/kisielk/errcheck" #used by emacs flycheck
packages="$packages github.com/laurent22/massren" #rename multiple files using text editor <https://github.com/laurent22/massren>
packages="$packages github.com/lukasmartinelli/pgfutter" #import csv and json into postgresql
packages="$packages github.com/maruel/panicparse/cmd/pp" # pipe stderr and format like that: `go run buggy.go |&pp`
packages="$packages github.com/monochromegane/the_platinum_searcher/..." #ag and ack replacement <https://github.com/monochromegane/the_platinum_searcher>
packages="$packages github.com/noraesae/orange-cat/cmd/orange" #markdown preview
packages="$packages github.com/nsf/gocode" #used by emacs auto complete
packages="$packages github.com/rakyll/boom" #http load generator (a-la ab)
packages="$packages github.com/rapidloop/rtop" #remote top over ssh
packages="$packages github.com/rlmcpherson/s3gof3r/gof3r" #s3 client
packages="$packages github.com/rogpeppe/godef" #used by emacs for jump to the definition of the expression at point
packages="$packages github.com/russross/blackfriday-tool" #markdown
packages="$packages github.com/schachmat/wego" #weather
packages="$packages github.com/zquestz/s" #open default browser and web search
packages="$packages golang.org/x/tools/cmd/godoc" #documentation
packages="$packages golang.org/x/tools/cmd/goimports" #used by emacs as `gofmt` command replacement for adding/removing golang import lines
packages="$packages golang.org/x/tools/cmd/gorename"
packages="$packages golang.org/x/tools/cmd/vet" #used by emacs flycheck

go get -v -u $packages
