(eval-after-load 'highlight-symbol
  '(progn
     (cond ((equal frame-background-mode 'light)
            (set-face-background 'highlight-symbol-face
                                 "paleturquoise")
            )
           ((equal frame-background-mode 'dark)
            ;; (set-face-attribute 'highlight-symbol-face nil
            ;;                     :foreground nil
            ;;                     :background "gray40")
            (set-face-background 'highlight-symbol-face
                                 "gray20")
            ))

     ;; (global-set-key (kbd "C-c d y ") 'highlight-symbol-at-point)
     (global-set-key (kbd "C-c d y n") 'highlight-symbol-next-with-repeat)
     (global-set-key (kbd "C-c d y p") 'highlight-symbol-prev-with-repeat)
     (global-set-key (kbd "C-c d y r") 'highlight-symbol-query-replace)
     (defun highlight-symbol-next-with-repeat ()
       (interactive)
       (my-with-repeat-while-press-last-key
         (highlight-symbol-next)))
     (defun highlight-symbol-prev-with-repeat ()
       (interactive)
       (my-with-repeat-while-press-last-key
         (highlight-symbol-prev)))

     (add-hook 'awk-mode-hook 'highlight-symbol-mode)
     (add-hook 'coffee-mode-hook 'highlight-symbol-mode)
     (add-hook 'conf-mode-hook 'highlight-symbol-mode)
     (add-hook 'conf-space-mode-hook 'highlight-symbol-mode)
     (add-hook 'conf-xdefaults-mode-hook 'highlight-symbol-mode)
     (add-hook 'css-mode-hook 'highlight-symbol-mode)
     (add-hook 'emacs-lisp-mode-hook 'highlight-symbol-mode)
     (add-hook 'haml-mode-hook 'highlight-symbol-mode)
     (add-hook 'haskell-mode-hook 'highlight-symbol-mode)
     (add-hook 'html-mode-hook 'highlight-symbol-mode)
     (add-hook 'java-mode-hook 'highlight-symbol-mode)
     (add-hook 'js-mode-hook 'highlight-symbol-mode)
     (add-hook 'lisp-mode-hook 'highlight-symbol-mode)
     (add-hook 'lua-mode-hook 'highlight-symbol-mode)
     (add-hook 'makefile-gmake-mode-hook 'highlight-symbol-mode)
     (add-hook 'markdown-mode-hook 'highlight-symbol-mode)
     (add-hook 'nxml-mode-hook 'highlight-symbol-mode)
     (add-hook 'org-mode-hook 'highlight-symbol-mode)
     (add-hook 'perl-mode-hook 'highlight-symbol-mode)
     (add-hook 'php-mode-hook 'highlight-symbol-mode)
     (add-hook 'rhtml-mode-hook 'highlight-symbol-mode)
     (add-hook 'ruby-mode-hook 'highlight-symbol-mode)
     (add-hook 'sass-mode-hook 'highlight-symbol-mode)
     (add-hook 'scss-mode-hook 'highlight-symbol-mode)
     (add-hook 'sgml-mode-hook 'highlight-symbol-mode)
     (add-hook 'sh-mode-hook 'highlight-symbol-mode)
     (add-hook 'shell-mode-hook 'highlight-symbol-mode)
     (add-hook 'sql-mode-hook 'highlight-symbol-mode)
     (add-hook 'xml-mode-hook 'highlight-symbol-mode)
     (add-hook 'yaml-mode-hook 'highlight-symbol-mode)
     ))
