(global-set-key (kbd "C-c d l b")
                (lambda ()
                  (interactive)
                  (eval-buffer)
                  (message (format "%s evaled" (buffer-name)))))
(global-set-key (kbd "C-c d l r")
                (lambda (start end)
                  (interactive "r")
                  (eval-region start end)
                  (message "Region evaled")))
