#!/usr/bin/env bash

# This file is part of Danil Kutkevich <danil@kutkevich.org> home.

confload() {
    local dir="${1}"

    if [ ! -d "$dir" ]; then
        printf >&2 "missing bash configuration directory %s\n" "$dir"
        return
    fi

    for cfg in ${dir}/*; do
        if [ -r "${cfg}" ]; then
            source "$cfg";
        else
            printf >&2 "unreadable bash configuration file %s\n" "$cfg"
        fi
    done
}
