#!/usr/bin/env bash

# This file is part of Danil Kutkevich <danil@kutkevich.org> home.

CFGDIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

source   "$CFGDIR"/confload
confload "$CFGDIR"/conf.d

export LANG=en_US.UTF-8
export LANGUAGE=en_US.UTF-8
export LC_TYPE=en_US.UTF-8
export LC_ALL=en_US.UTF-8

# Disable the XOFF (Ctrl-s) keystroke
# <http://superuser.com/questions/124845/can-you-disable-the-ctrl-s-xoff-keystroke-in-putty#155875>,
# <https://wiki.archlinux.org/index.php/Readline#History>.
stty -ixon

# export PAGER="/usr/bin/less --IGNORE-CASE --LONG-PROMPT" # not working(
export HISTSIZE=50000
export HISTFILESIZE=50000
export HISTCONTROL=ignoredups:erasedups

# See /usr/share/terminfo/*/
# export TERM=rxvt-256color
[ "$TERM" = "xterm" ] && export TERM="xterm-256color" # <http://ricochen.wordpress.com/2011/07/23/mac-os-x-lion-terminal-color-remote-access-problem-fix>
export TERMINAL="xterm-256color" # "xterm" # safe fallback/backup terminal

[ -x "$(command -v vim)" ] && export EDITOR="vim" # export EDITOR="/usr/bin/emacsclient -t" # safe fallback/backup editor
# [ -x "$(command -v emacs)" ] && export ALTERNATE_EDITOR="/usr/bin/emacs"

# export PATH="$HOME"/.cask/bin:"$PATH" # emacs cask <https://github.com/cask/cask>
export PATH="$HOME"/.local/bin:"$PATH" # tmux make installs here and pip (python package management system) run `python-install-all`
export PATH="$HOME"/.local/sbin:"$PATH"
export PATH="$HOME"/.local/usr/bin:"$PATH" # xxkb make installs here
export PATH="$HOME"/.local/usr/sbin:"$PATH" # powertop make installs here
export PATH="$HOME"/.local/usr/local/bin:"$PATH" # dwm make installs here
export PATH="$HOME"/.local/usr/local/sbin:"$PATH" # dwm make installs here
export PATH="$HOME"/.local/usr/local/usr/bin:"$PATH"
export PATH="$HOME"/sbin:"$PATH"
export PATH="$HOME"/bin:"$PATH" # clib c package manager installs here <https://github.com/clibs/clib> run `c-install-all`

export MANPATH="$HOME"/.local/usr/share/man:"$MANPATH"
export MANPATH="$HOME"/.local/usr/local/share/man:"$MANPATH"

[ -x "$(command -v emacs)" ] && export GIT_EDITOR='emacs'
# export GIT_PAGER=""

# Aliases.
# <http://askubuntu.com/questions/22037/aliases-not-available-when-using-sudo#22043>.
# alias less=$PAGER
alias ag='ag --width=5000'
alias ls='ls --color'
alias sudo='sudo '

# User XDG base directory environment variable
# <https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html>
# <https://wiki.archlinux.org/title/XDG_Base_Directory#User_directories>.
export XDG_CONFIG_HOME="$HOME"/.config
export XDG_DATA_HOME="$HOME"/.local/share

[ -f "$HOME"/.env ] && . "$HOME"/.env # dotenv

[ -f "$HOME"/.netrc/.netrc ] && export NETRC="$HOME"/.netrc/.netrc

# <https://askubuntu.com/questions/210210/pkg-config-path-environment-variable#210235>.
export PKG_CONFIG_PATH="$PKG_CONFIG_PATH":/usr/lib/pkgconfig
export PKG_CONFIG_PATH="$PKG_CONFIG_PATH":/usr/lib/x86_64-linux-gnu/pkgconfig
export PKG_CONFIG_PATH="$PKG_CONFIG_PATH":/usr/share/pkgconfig

# bc calculator
# <https://askubuntu.com/questions/621017/how-to-set-default-scale-for-bc-calculator#939407>.
export BC_ENV_ARGS=/home/danil/.bc

# Debian/Ubuntu.
export DEBFULLNAME="Danil Kutkevich"
export DEBEMAIL="danil@kutkevich.org"

# X11
# <https://wiki.archlinux.org/title/Intel_graphics#DRI3_issues>.
# export MESA_LOADER_DRIVER_OVERRIDE=iris
# export LIBGL_DRI3_DISABLE=1

# Qt
# <https://wiki.archlinux.org/title/qt>,
# <https://wiki.archlinux.org/title/Uniform_look_for_Qt_and_GTK_applications>.
# QT_STYLE_OVERRIDE
export QT_QPA_PLATFORMTHEME=qt5ct

# Qt <https://wiki.archlinux.org/title/HiDPI#Qt_5>.
# export QT_SCALE_FACTOR=1
# export QT_SCREEN_SCALE_FACTORS=1
export QT_AUTO_SCREEN_SCALE_FACTOR=1
