add_newline = false # disable the newline at the start of the prompt

format = """\
$username\
$hostname\
$shlvl\
$cmd_duration\
${custom.load}\
$jobs\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$hg_branch\
$docker_context\
$memory_usage\
${custom.datetime}\
$line_break\
$character"""

[username]
show_always = true
format = "[$user]($style)"
style_user = "bold green"

[hostname]
ssh_only = false
format = "[@$hostname]($style) "
style = "bold green"

[jobs]
disabled = false
threshold = 0
format = "[jobs:$number]($style) "

[git_branch]
format = "[$branch]($style) "

[git_status]
format = '[$all_status$ahead_behind]($style) '
style = "bold purple"

[directory]
truncate_to_repo = false
truncation_length = 999
style = "bold blue"

[memory_usage]
disabled = false
threshold = 90
format = "[${ram}( ${swap})]($style) "

[cmd_duration]
min_time = 10000
format = "[$duration](bold yellow) "
show_notifications = true

[custom.datetime]
disabled = false
command = """date +"%d-%b-%Y %H:%M:%S%Z""""
when = """ true """
format = "[$output]($style)"
style = "bold white"

[custom.load]
disabled = false
command = """
# Prompt load average
# <http://www.gilesorr.com/bashprompt/prompts/load.html>,
# <http://stackoverflow.com/questions/1738665/showing-only-the-uptime-from-uptime-unix/1738675#1740333>.
load_string="$(uptime)"
load_string=${load_string/#*average: }
load_string=${load_string%%,*}
tmp=$(echo ${load_string}*100 | bc)
let load100=${tmp%.*}
if [[ ${load100} -ge 100 ]]; then
    echo -n "load:${load_string}"
fi
"""
when = """ true """
format = "[$output]($style) "
style = "bold white"
