#!/usr/bin/env bash

# This file is part of Danil Kutkevich <danil@kutkevich.org> home.

export PATH="$HOME"/node_modules/.bin:"$PATH" # TROUBLESHOOTING: Do NOT give priority to npm executables!!! # node.js and npm

# n (Node.js version manager).
# <https://github.com/tj/n>
# DEPRECATED: Instead installing Node.js from homebrew.
# export N_PREFIX="$HOME"
# [[ :$PATH: == *":$N_PREFIX/bin:"* ]] || PATH+=":$N_PREFIX/bin"

# nvm (Node.js version manager)
# DEPRECATED: Instead installing Node.js from homebrew.
# export NVM_DIR="$HOME/.nvm"
# [ -s "$NVM_DIR/nvm.sh" ] && source "$NVM_DIR/nvm.sh" # this loads nvm
# [[ -r "$NVM_DIR/bash_completion" ]] && source "$NVM_DIR/bash_completion"
