#!/usr/bin/env bash

# This file is part of Danil Kutkevich <danil@kutkevich.org> home.

# Rust
# rust toolchain installer
# <https://rustup.rs>.
[ -f "$HOME"/.cargo/env ] && source "$HOME"/.cargo/env # adding `"$HOME"/.cargo/bin` to your PATH to be able to run the installed binaries
export PATH="$HOME"/.cargo/bin:"$PATH"
