#!/usr/bin/env bash

# This file is part of Danil Kutkevich <danil@kutkevich.org> home.

# Nix
# <https://github.com/homebrew/brew>.
# <https://itsfoss.com/ubuntu-install-nix-package-manager>,
# <https://nix.dev/manual/nix/2.18/installation/installing-binary.html#single-user-installation>.


if [ ! -f /home/danil/.nix-profile/etc/profile.d/nix.sh ]; then
    # printf >&2 "missing Nix\n"
    return
fi

source /home/danil/.nix-profile/etc/profile.d/nix.sh
export NIXPKGS_ALLOW_UNFREE=1
