# This file is part of Danil Kutkevich <danil@kutkevich.org> home.
# Light theme.

[colors.primary]
background = "#ffffff"
foreground = "#000000"

# Normal colors.
[colors.normal]
black   = "#000000" # 1.
red     = "#cd0000" # 2. "red3"
green   = "#00cd00" # 3. "green3"
yellow  = "#cdcd00" # 4. "yellow3"
blue    = "#3f69ee" # 5. "blue2" "#2222ee" "#5454ee" "#3f69ee"
magenta = "#cd00cd" # 6. "magenta3"
cyan    = "#00cdcd" # 7. "cyan3"
white   = "#e5e5e5" # 8. "gray90"

# Bright colors.
[colors.bright]
black   = "#7f7f7f" # 9.
red     = "#ff0000" # 10.
green   = "#00ff00" # 11.
yellow  = "#ffff00" # 12.
blue    = "#5c5cff" # 13.
magenta = "#ff00ff" # 14.
cyan    = "#00ffff" # 15.
white   = "#ffffff" # 16.

[colors.cursor]
cursor = "#ff0000"

[colors.selection]
text = "CellBackground"
